development:
  # stripe
  stripe_publishable_key: pk_test_51JacIpBlNtGZVYcswCr6lpnQOCkQvdI7UbECzxyM62Br2oDyj5aHKhdQRE4I3fdU07q4hPu8tLWdURsOvKCjYHY100r0cXIs85
  stripe_secret_key: sk_test_51JacIpBlNtGZVYcskV0hgw7eNtErFvRvQFXyrBjyfobSaDt5pV7OKm9Faqseitdxxn7DkXIR9EfNcsh1oPM3WpJ100DPOhaCD3
