# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Command.create(name: "ジャンプ") 
Command.create(name: "小ジャンプ") 
Command.create(name: "大ジャンプ") 
Command.create(name: "A") 
Command.create(name: "上強攻撃") 
Command.create(name: "下強攻撃") 
Command.create(name: "前強攻撃") 
Command.create(name: "後強攻撃") 
Command.create(name: "空NA") 
Command.create(name: "空上A") 
Command.create(name: "空下A") 
Command.create(name: "空前A") 
Command.create(name: "空後A") 
Command.create(name: "B") 
Command.create(name: "上B") 
Command.create(name: "下B") 
Command.create(name: "前横B") 
Command.create(name: "後横B") 
Command.create(name: "空NB") 
Command.create(name: "空上B") 
Command.create(name: "空下空B") 
Command.create(name: "空前横B") 
Command.create(name: "空後横B")
Command.create(name: "低空ヒット")
Command.create(name: "次") 
Command.create(name: "前投げ") 
Command.create(name: "後投げ") 
Command.create(name: "上投げ") 
Command.create(name: "下投げ") 
Fighter.create(fighter_id:1, name: "マリオ") 
Fighter.create(fighter_id:2, name: "ドンキーコング") 
Fighter.create(fighter_id:3, name: "リンク") 
Fighter.create(fighter_id:4, name: "サムス.ダークサムス")
Fighter.create(fighter_id:5, name: "ヨッシー")
Fighter.create(fighter_id:6, name: "カービィ")
Fighter.create(fighter_id:7, name: "フォックス")
Fighter.create(fighter_id:8, name: "ピカチュウ")
Fighter.create(fighter_id:9, name: "ルイージ")
Fighter.create(fighter_id:10, name: "ネス")
Fighter.create(fighter_id:11, name: "キャプテン・ファルコン")
Fighter.create(fighter_id:12, name: "プリン")
Fighter.create(fighter_id:13, name: "ピーチ.デイジー")
Fighter.create(fighter_id:14, name: "クッパ")
Fighter.create(fighter_id:15, name: "アイスクライマー")
Fighter.create(fighter_id:16, name: "シーク")
Fighter.create(fighter_id:17, name: "ゼルダ")
Fighter.create(fighter_id:18, name: "ドクターマリオ")
Fighter.create(fighter_id:19, name: "ピチュー")
Fighter.create(fighter_id:20, name: "ファルコ")
Fighter.create(fighter_id:21, name: "マルス")
Fighter.create(fighter_id:22, name: "ルキナ")
Fighter.create(fighter_id:23, name: "こどもリンク")
Fighter.create(fighter_id:24, name: "ガノンドロフ")
Fighter.create(fighter_id:25, name: "ミュウツー")
Fighter.create(fighter_id:26, name: "ロイ")
Fighter.create(fighter_id:27, name: "クロム")
Fighter.create(fighter_id:28, name: "Mr.ゲーム＆ウォッチ")
Fighter.create(fighter_id:29, name: "メタナイト")
Fighter.create(fighter_id:30, name: "ピット")
Fighter.create(fighter_id:31, name: "ブラックピット")
Fighter.create(fighter_id:32, name: "ゼロスーツサムス")
Fighter.create(fighter_id:33, name: "ワリオ")
Fighter.create(fighter_id:34, name: "スネーク")
Fighter.create(fighter_id:35, name: "アイク")
Fighter.create(fighter_id:36, name: "ゼニガメ")
Fighter.create(fighter_id:37, name: "フシギソウ")
Fighter.create(fighter_id:38, name: "リザードン")
Fighter.create(fighter_id:39, name: "ディディーコング")
Fighter.create(fighter_id:40, name: "リュカ")
Fighter.create(fighter_id:41, name: "ソニック")
Fighter.create(fighter_id:42, name: "デデデ")
Fighter.create(fighter_id:43, name: "ピクミン＆オリマー")
Fighter.create(fighter_id:44, name: "ルカリオ")
Fighter.create(fighter_id:45, name: "ロボット")
Fighter.create(fighter_id:46, name: "トゥーンリンク")
Fighter.create(fighter_id:47, name: "ウルフ")
Fighter.create(fighter_id:48, name: "むらびと")
Fighter.create(fighter_id:49, name: "ロックマン")
Fighter.create(fighter_id:50, name: "Wii Fit トレーナー")
Fighter.create(fighter_id:51, name: "ロゼッタ＆チコ")
Fighter.create(fighter_id:52, name: "リトル・マック")
Fighter.create(fighter_id:53, name: "ゲッコウガ")
Fighter.create(fighter_id:54, name: "Miiファイター（格闘タイプ）")
Fighter.create(fighter_id:55, name: "Miiファイター（剣術タイプ）")
Fighter.create(fighter_id:56, name: "Miiファイター（射撃タイプ）")
Fighter.create(fighter_id:57, name: "パルテナ")
Fighter.create(fighter_id:58, name: "パックマン")
Fighter.create(fighter_id:59, name: "ルフレ")
Fighter.create(fighter_id:60, name: "シュルク")
Fighter.create(fighter_id:61, name: "クッパJr.")
Fighter.create(fighter_id:62, name: "ダックハント")
Fighter.create(fighter_id:63, name: "リュウ")
Fighter.create(fighter_id:64, name: "ケン")
Fighter.create(fighter_id:65, name: "クラウド")
Fighter.create(fighter_id:66, name: "カムイ")
Fighter.create(fighter_id:67, name: "ベヨネッタ")
Fighter.create(fighter_id:68, name: "インクリング")
Fighter.create(fighter_id:69, name: "リドリー")
Fighter.create(fighter_id:70, name: "シモン.リヒター")
Fighter.create(fighter_id:71, name: "キングクルール")
Fighter.create(fighter_id:72, name: "しずえ")
Fighter.create(fighter_id:73, name: "ガオガエン")
Fighter.create(fighter_id:74, name: "パックンフラワー")
Fighter.create(fighter_id:75, name: "ジョーカー")
Fighter.create(fighter_id:76, name: "勇者")
Fighter.create(fighter_id:77, name: "バンジョー＆カズーイ")
Fighter.create(fighter_id:78, name: "テリー")
Fighter.create(fighter_id:79, name: "ベレト.ベレス")
Fighter.create(fighter_id:80, name: "ミェンミェン")
Fighter.create(fighter_id:81, name: "スティーブ.アレックス")
Fighter.create(fighter_id:82, name: "セフィロス")
Fighter.create(fighter_id:83, name: "ホムラ")
Fighter.create(fighter_id:84, name: "ヒカリ")

Admin.create(name: 'testtest', email: 'test@test.com', password: 'testtest' )

Genre.create(name: '撃墜用')
Genre.create(name: 'ダメージ用')

Startposition.create(name: '地上')
Startposition.create(name: '空中')
